// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/

package reset

func (PackageInfo *PackageInfo) Reset() {
	if PackageInfo == nil {
		return
	}
	PackageInfo.Name = ""
	PackageInfo.Path = ""
	PackageInfo.Structs = PackageInfo.Structs[:0]
	PackageInfo.i = 0
	PackageInfo.str = ""
	if PackageInfo.strP != nil {
		*PackageInfo.strP = ""
	}
	PackageInfo.s = PackageInfo.s[:0]
	clear(PackageInfo.m)
	if PackageInfo.child != nil {
		var resetter interface{} = PackageInfo.child
		if r, ok := resetter.(interface{ Reset() }); ok {
			r.Reset()
		}
	}

}

func (StructInfo *StructInfo) Reset() {
	if StructInfo == nil {
		return
	}
	StructInfo.Name = ""
	StructInfo.Fields = StructInfo.Fields[:0]

}

func (StructField *StructField) Reset() {
	if StructField == nil {
		return
	}
	StructField.Name = ""

}
