// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/

package reset

func (PackageInfo *PackageInfo) Reset() {
	if PackageInfo == nil {
		return
	}
	PackageInfo.Name = ""
	PackageInfo.Path = ""
	PackageInfo.Structs = PackageInfo.Structs[:0]

}

func (StructInfo *StructInfo) Reset() {
	if StructInfo == nil {
		return
	}
	StructInfo.Name = ""
	StructInfo.Fields = StructInfo.Fields[:0]

}

func (StructField *StructField) Reset() {
	if StructField == nil {
		return
	}
	StructField.Name = ""

}

func (StructTest *StructTest) Reset() {
	if StructTest == nil {
		return
	}
	StructTest.i = 0
	StructTest.str = ""
	if StructTest.strP != nil {
		*StructTest.strP = ""
	}
	StructTest.s = StructTest.s[:0]
	clear(StructTest.m)
	if StructTest.child != nil {
		var resetter interface{} = StructTest.child
		if r, ok := resetter.(interface{ Reset() }); ok {
			r.Reset()
		}
	}

}
