// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/

package models

func (MemStorage *MemStorage) Reset() {
	if MemStorage == nil {
		return
	}
	clear(MemStorage.Gauge)
	clear(MemStorage.Counter)

}
