// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/

package service

func (AgentService *AgentService) Reset() {
	if AgentService == nil {
		return
	}
	if AgentService.metricsCollector != nil {
		var resetter interface{} = AgentService.metricsCollector
		if r, ok := resetter.(interface{ Reset() }); ok {
			r.Reset()
		}
	}
	if AgentService.metricsSender != nil {
		var resetter interface{} = AgentService.metricsSender
		if r, ok := resetter.(interface{ Reset() }); ok {
			r.Reset()
		}
	}
	if AgentService.model != nil {
		var resetter interface{} = AgentService.model
		if r, ok := resetter.(interface{ Reset() }); ok {
			r.Reset()
		}
	}
	if AgentService.send != nil {
		var resetter interface{} = AgentService.send
		if r, ok := resetter.(interface{ Reset() }); ok {
			r.Reset()
		}
	}
	AgentService.rateLimit = 0

}
